<?php
  // Arquivo para conectar ao banco de dados
  try{ // Tente...
    $conexaobd = new PDO("mysql:host=".$servidor.";dbname=".$banco.";charset=utf8", $usuarioconf, $senhaconf); // ...conectar...
  } catch (PDOException $e) { // ...se não der, pegue a exceção, atribua a uma variável...
    die ("Erro ao se conectar com o banco de dados: " . $e->getMessage()); // ...e mostre uma mensagem amigável :)
  }
?>
